# run solution tester

name: Advent of Code 2020 Solution Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: env
      run: set > env.txt
    - name: Test Solutions
      id: testsolutions
      run: |
        pip install numpy
        python test.py | tee results.txt
    - uses: actions/upload-artifact@v2
      with:
        path: results.txt
    - uses: actions/upload-artifact@v2
      with:
        path: env.txt
